/**
 * NFKC pinned to the Unicode version the committed fixtures were exported against.
 *
 * `String.prototype.normalize` follows the host ICU, which is ahead of the database CPython
 * bundles. Measuring the gap rather than assuming it (see `fixtures/runtime/unicode-nfkc-vectors.json`
 * and `runtime/test/unicode-nfkc.test.ts`) found it to be narrow and precisely bounded: of every
 * input this migration cares about, the two runtimes disagree on exactly the code points assigned
 * in Unicode 16.0 that carry a compatibility decomposition. CPython 15.0.0 does not know them, so
 * it leaves them alone; ICU decomposes them.
 *
 * That gap is not cosmetic. All thirty-six of them decompose to ASCII letters and digits, which is
 * exactly the domain of `realtime/recall.py`'s tokenizer -- so under the host ICU an outlined `𜳰`
 * would tokenize as `0` and match a memory containing a zero, while the oracle would not match it
 * at all. Which memories a model is shown is contract-visible.
 *
 * The fix is narrow because the problem turned out to be narrow: hold those code points back from
 * the host normalizer, then let it do everything else. That is far less than vendoring a
 * normalization table, and it stays correct as ICU advances -- a code point assigned after 15.0.0
 * is by definition one CPython 15.0.0 does not decompose.
 */

import { PINNED_UNICODE_VERSION } from './unicode-tables.js'

export { PINNED_UNICODE_VERSION }

/**
 * Code points assigned in Unicode 16.0 that ICU gives a compatibility decomposition and the pinned
 * database does not. Generated by `scripts/generate_unicode_tables.py --nfkc-holdback`; a test
 * fails if the host ICU disagrees with this list, in either direction.
 */
const HOLDBACK_RANGES: readonly (readonly [number, number])[] = [
  // Outlined capital letters A-Z, U+1CCD6..U+1CCEF.
  [0x1_cc_d6, 0x1_cc_ef],
  // Outlined digits 0-9, U+1CCF0..U+1CCF9.
  [0x1_cc_f0, 0x1_cc_f9],
]

const HOLDBACK = new Set<number>()
for (const [start, end] of HOLDBACK_RANGES) {
  for (let codePoint = start; codePoint <= end; codePoint += 1) HOLDBACK.add(codePoint)
}

/** Every code point held back from the host normalizer, for the test that verifies the set. */
export const NFKC_HOLDBACK_CODE_POINTS: readonly number[] = [...HOLDBACK].sort((a, b) => a - b)

/**
 * A private-use code point that stands in for a held-back character during normalization.
 *
 * Substitution rather than splitting the string, because normalization is contextual: a combining
 * mark either side of a boundary would compose differently if the two halves were normalized
 * separately. A single unassigned code point with no decomposition and no combining class passes
 * through NFKC untouched and cannot merge with its neighbours.
 */
const PLACEHOLDER_BASE = 0xf_00_00

/**
 * NFKC as the pinned Unicode version would compute it.
 *
 * Use this anywhere the result is contract-visible -- recall scoring, confirmation matching, any
 * text a model or a golden will see. Plain `.normalize('NFKC')` is fine only for text that never
 * leaves the process.
 */
export function normalizeNfkcPinned(text: string): string {
  const characters = [...text]
  const held: number[] = []
  let substituted = ''
  for (const character of characters) {
    const codePoint = character.codePointAt(0)
    if (codePoint !== undefined && HOLDBACK.has(codePoint)) {
      substituted += String.fromCodePoint(PLACEHOLDER_BASE + held.length)
      held.push(codePoint)
      continue
    }
    substituted += character
  }
  if (held.length === 0) return text.normalize('NFKC')

  const normalized = substituted.normalize('NFKC')
  let restored = ''
  for (const character of normalized) {
    const codePoint = character.codePointAt(0)
    if (
      codePoint !== undefined
      && codePoint >= PLACEHOLDER_BASE
      && codePoint < PLACEHOLDER_BASE + held.length
    ) {
      restored += String.fromCodePoint(held[codePoint - PLACEHOLDER_BASE]!)
      continue
    }
    restored += character
  }
  return restored
}

/**
 * The pipeline `recall.py` runs: pinned NFKC, then lowercase.
 *
 * Kept together because the two stages are only correct as a pair -- lowercasing before normalizing
 * gives a different answer for some inputs, and the oracle normalizes first.
 */
export function normalizeAndLowerPinned(text: string): string {
  return normalizeNfkcPinned(text).toLowerCase()
}
