String tr(String language, String text) =>
    language == 'zh' ? (_zh[text] ?? text) : text;
const _zh = <String, String>{
  'Speech detection threshold': '语音检测阈值',
  'Not connected': '尚未连接',
  'Connecting': '正在连接',
  'Connected': '已连接',
  'Listening': '正在聆听',
  'Settings': '设置',
  'Text chat': '文字聊天',
  'Live conversation': '实时对话',
  'Connect': '连接',
  'Disconnect': '断开连接',
  'Start conversation': '开始对话',
  'Mute': '静音',
  'Unmute': '取消静音',
  'Speaker': '扬声器',
  'End call': '结束通话',
  'You': '你',
  'Type a message…': '输入消息…',
  'Send message': '发送消息',
  'Hold to speak': '按住说话',
  'Release to transcribe': '松开转文字',
  'Cancel': '取消',
  'Transcribing…': '正在识别…',
  'Needs your confirmation': '需要你确认',
  'Approve': '批准',
  'Approve for session': '本会话批准',
  'Decline': '拒绝',
  'Expired / waiting for host': '已过期或等待主机更新',
  'Server': '服务器',
  'Token': '连接令牌',
  'Language': '语言',
  'Media transport': '音频传输',
  'Scan pairing code': '扫描配对码',
  'Feishu login': '飞书登录',
  'This build has no login service configured': '此构建尚未配置飞书登录服务',
  'Save and connect': '保存并连接',
  'Forget connection': '忘记连接',
  'Pair with this host?': '与此主机配对？',
  'Pair': '配对',
  'Auto': '自动',
  'Relay': '主机中继',
  'Voice recognition': '语音识别',
  'Message too long': '消息过长，请缩短后发送',
  'Tasks': '任务',
  'Results': '结果',
  'Your conversation appears here': '对话内容将显示在这里',
  'Connect to your Nova host to begin': '连接 Nova 主机以开始',
  'Microphone permission denied': '请在系统设置中允许麦克风访问',
  'Edit before sending': '可编辑后发送',
  'No transcription. Draft preserved.': '未能识别语音，原草稿已保留。',
  'Unable to start microphone': '无法启动录音，请重试',
  'Message not accepted. Draft preserved.': '消息未被接受，草稿已保留',
  'Transcription timed out. Draft preserved.': '识别超时，原草稿已保留。',
  'No acknowledgement. Check the conversation before sending again. Draft preserved.':
      '未收到发送确认，请先查看回复，避免重复发送。草稿已保留。',
};
