String tr(String language, String text) =>
    language == 'zh' ? (_zh[text] ?? text) : text;
const _zh = <String, String>{
  'Connection settings': '连接设置',
  'Done': '完成',
  'Manual connection': '手动连接',
  'The connection token is stored securely on this device.': '连接密钥仅安全保存在这台设备上。',
  'Enabled when a deployment configures a login service.': '由部署方配置登录服务后启用。',
  'Scan the Nova QR code on your host to fill the address and securely save the connection.':
      '扫描主机上的 Nova 二维码，自动填入地址并安全保存连接凭据。',
  'Raise in noisy environments; lower for quiet speech.':
      '环境嘈杂时调高；轻声说话时调低。当前阈值',
  'The first launch follows your system language. Disconnect before changing it.\n\nThe AI prompt language applies on the next supported host connection; it does not change the voice model or guarantee the reply language.':
      '首次按系统首选语言设置，之后保留你的选择。更改语言前请先断开连接。\n\nAI 仅切换 system prompt 的语言，不保证回复始终使用该语言；不自动识别或切换语言，也不更换语音模型或音色。\n\nAI 提示词在下次连接支持此设置的主机时生效。',

  'What would you like to talk about?': '有什么想聊的？',
  'Latest messages': '查看最新消息',
  'Scan Nova QR code': '扫描 Nova 配对码',
  'Speech detection threshold': '语音检测阈值',
  'Not connected': '尚未连接',
  'Connecting': '正在连接',
  'Connected': '已连接',
  'Listening': '正在聆听',
  'Settings': '设置',
  'Text chat': '文字聊天',
  'Live conversation': '实时对话',
  'Connect': '连接',
  'Disconnect': '断开连接',
  'Start conversation': '开始对话',
  'Mute': '静音',
  'Unmute': '取消静音',
  'Speaker': '扬声器',
  'End call': '结束通话',
  'You': '你',
  'Type a message…': '输入消息…',
  'Send message': '发送消息',
  'Hold to speak': '按住说话',
  'Release to transcribe': '松开转文字',
  'Cancel': '取消',
  'Transcribing…': '正在识别…',
  'Needs your confirmation': '需要你确认',
  'Approve': '批准',
  'Approve for session': '本会话批准',
  'Decline': '拒绝',
  'Expired / waiting for host': '已过期或等待主机更新',
  'Server': '服务器',
  'Token': '连接令牌',
  'Language': '语言',
  'Media transport': '音频传输',
  'Scan pairing code': '扫描配对码',
  'Feishu login': '飞书登录',
  'This build has no login service configured': '此构建尚未配置飞书登录服务',
  'Save and connect': '保存并连接',
  'Forget connection': '忘记连接',
  'Pair with this host?': '与此主机配对？',
  'Pair': '配对',
  'Auto': '自动',
  'Relay': '主机中继',
  'Voice recognition': '语音识别',
  'Message too long': '消息过长，请缩短后发送',
  'Tasks': '任务',
  'Results': '结果',
  'Your conversation appears here': '对话内容将显示在这里',
  'Connect to your Nova host to begin': '连接 Nova 主机以开始',
  'Microphone permission denied': '请在系统设置中允许麦克风访问',
  'Edit before sending': '可编辑后发送',
  'No transcription. Draft preserved.': '未能识别语音，原草稿已保留。',
  'Unable to start microphone': '无法启动录音，请重试',
  'Message not accepted. Draft preserved.': '消息未被接受，草稿已保留',
  'Transcription timed out. Draft preserved.': '识别超时，原草稿已保留。',
  'No acknowledgement. Check the conversation before sending again. Draft preserved.':
      '未收到发送确认，请先查看回复，避免重复发送。草稿已保留。',
};
