export type EnvironmentOwner =
  | 'core' | 'qwen' | 'stepfun' | 'ark' | 'deepseek' | 'volcengine' | 'codex' | 'search' | 'camera'
  | 'mobile' | 'autoglm' | 'telemetry' | 'host_private'

export interface EnvironmentVariableContract {
  readonly name: string
  readonly owner: EnvironmentOwner
  readonly secret: boolean
  readonly public: boolean
  readonly required: 'never' | 'when_selected'
  readonly defaultLabel: string | null
  readonly descriptionEn: string
  readonly descriptionZh: string
}

type Row = readonly [
  name: string,
  owner: EnvironmentOwner,
  secret: boolean,
  publicValue: boolean,
  required: 'never' | 'when_selected',
  defaultLabel: string | null,
  descriptionEn: string,
  descriptionZh: string,
]

const rows: readonly Row[] = [
  ['NOVA_WORKBENCH_ACCEPTANCE_REPORT', 'host_private', false, false, 'never', null, 'Workbench acceptance report path.', 'Workbench acceptance report path.'],
  ['NOVA_WORKBENCH_ACCEPTANCE_MANIFEST', 'host_private', false, false, 'never', null, 'Workbench acceptance manifest path.', 'Workbench acceptance manifest path.'],
  ['XDG_CONFIG_HOME', 'host_private', false, false, 'never', null, 'Host configuration directory.', 'Host configuration directory.'],
  ['GIT_CONFIG_GLOBAL', 'host_private', false, false, 'never', null, 'Host Git configuration file.', 'Host Git configuration file.'],
  ['OPENROUTER_API_KEY', 'core', true, true, 'never', null, 'OpenRouter credential for Jev.', 'OpenRouter credential for Jev.'],
  ['COMPOSIO_API_KEY', 'core', true, true, 'never', null, 'Composio application connection credential.', 'Composio application connection credential.'],

  ['MEMORY_LEDGER_PATH', 'core', false, true, 'never', '~/.nova-audio-agent/workspace-graph.sqlite', 'Canonical memory ledger SQLite path; retains the v0.3 storage location.', '统一记忆账本 SQLite 路径，兼容 v0.3 已有存储位置。'],
  ['WORKSPACE_GRAPH_PATH', 'host_private', false, false, 'never', null, 'Legacy alias for the memory ledger path.', '记忆账本路径的历史兼容别名。'],
  ['AOQ_API_HOST', 'host_private', false, false, 'never', null, 'AOQ API host used by the remote server.', '远程服务使用的北京 AOQ API 主机。'],
  ['SERVER_MEDIA_MODE', 'host_private', false, false, 'never', null, 'Remote media mode: relay, aoq_chat or aoq_runtime.', '远程媒体模式：relay、aoq_chat 或 aoq_runtime。'],
  ['BACKEND', 'host_private', false, false, 'never', 'node', 'Node-only desktop backend guard.', '仅 Node 的桌面后端守卫。'],
  ['MODEL_BASE_URL', 'core', false, true, 'never', 'DashScope compatible endpoint', 'FastBrain compatible API endpoint.', 'FastBrain 兼容 API 地址。'],
  ['MODEL_API_KEY', 'core', true, true, 'never', null, 'Optional generic support-model API credential override.', '可选的通用辅助模型 API 凭据覆盖。'],
  ['FAST_MODEL', 'core', false, true, 'never', 'qwen3-vl-plus', 'FastBrain model.', 'FastBrain 模型。'],
  ['WATCH_MODEL', 'core', false, true, 'never', 'fast model', 'Watch model override.', 'Watch 模型覆盖。'],
  ['SUPPORT_MODEL', 'core', false, true, 'never', 'qwen-plus', 'Shared support LLM for proactive communication, intake, task verification and personal content.', '主动沟通、任务接入、任务验收和个人内容共用的辅助 LLM。'],
  ['COMPRESSOR_MODEL', 'core', false, true, 'never', 'qwen-flash', 'Memory compressor model.', '记忆压缩模型。'],
  ['PIPELINE_MODE', 'core', false, true, 'never', 'integrated', 'Product pipeline shape: integrated or cascaded.', '产品管线形态：集成或级联。'],
  ['NEWS_LANGUAGE', 'core', false, true, 'never', 'en', 'Native RSS language: zh-CN or en. Desktop supplies OS language independently of UI preference; applied at runtime start.', '原生 RSS 语言：zh-CN 或 en；桌面传入系统语言，独立于界面偏好，运行时启动时生效。'],
  ['PROMPT_LANGUAGE', 'core', false, true, 'never', 'zh-CN', 'AI system prompt language: zh-CN or en; desktop supplies its saved preference.', 'AI system prompt 语言：zh-CN 或 en；桌面端会提供其保存的偏好。'],
  ['CONVERSATION_VISION_ENABLED', 'camera', false, true, 'never', 'false', 'Attach a default-camera frame to user turns on verified cascaded VLMs.', '为已确认支持图片的级联模型附加默认摄像头画面。'],
  ['MONITOR_CAMERA_DEVICE_ID', 'camera', false, true, 'never', null, 'Exact monitor camera device ID; empty uses the default device.', '监控摄像头设备 ID；空值使用默认设备。'],
  ['CAMERA_MODULE_ENABLED', 'camera', false, true, 'never', 'true', 'Enable independent Vision monitoring.', '启用独立视觉监控。'],
  ['INTEGRATED_PROVIDER', 'core', false, true, 'never', 'qwen', 'Integrated realtime provider.', '集成实时提供方。'],
  ['CASCADE_ENDPOINTING_PROVIDER', 'core', false, true, 'never', 'auto', 'Cascaded endpointing provider.', '级联端点检测提供方。'],
  ['CASCADE_ASR_PROVIDER', 'core', false, true, 'never', 'volcengine', 'Cascaded ASR provider.', '级联 ASR 提供方。'],
  ['CASCADE_LLM_PROVIDER', 'core', false, true, 'never', 'deepseek', 'Cascaded LLM provider.', '级联 LLM 提供方。'],
  ['CASCADE_LLM_MODEL', 'core', false, true, 'never', 'provider default', 'Cascaded LLM model override.', '级联 LLM 模型覆盖。'],
  ['CASCADE_TTS_PROVIDER', 'core', false, true, 'never', 'volcengine', 'Cascaded TTS provider.', '级联 TTS 提供方。'],
  ['EXECUTOR', 'core', false, true, 'never', null, 'Optional single executor selector; unset selects none.', '可选的单执行器选择器；未设置时不选择执行器。'],
  ['EXECUTORS', 'core', false, true, 'never', null, 'Optional ordered executor list; unset selects none.', '可选的有序执行器列表；未设置时不选择执行器。'],
  ['CODING_PROGRESS_NARRATION', 'core', false, true, 'never', 'smart', 'Coding progress narration.', '编程进度播报模式。'],
  ['PROACTIVITY_PRESET', 'core', false, true, 'never', 'balanced', 'Proactivity preset.', '主动性预设。'],
  ['SUGGESTION_COOLDOWN', 'core', false, true, 'never', 'preset', 'Suggestion cooldown override in seconds.', '建议冷却秒数覆盖。'],
  ['FRESH_WINDOW', 'core', false, true, 'never', 'preset', 'Fresh-context window override in seconds.', '新鲜上下文窗口秒数覆盖。'],
  ['CODEX_APPROVAL_MODE', 'codex', false, true, 'never', 'ask', 'Coding approval mode for Codex and ACP backends; Pi refuses ask.', '编程审批模式，适用于 Codex 与 ACP 执行器；Pi 不接受询问模式。'],
  ['CLARIFICATION_DEPTH', 'core', false, true, 'never', 'balanced', 'Maximum clarification depth for intake.', '意图理解的最大澄清深度。'],
  ['PLAN_READBACK', 'core', false, true, 'never', 'summary', 'Plan readback mode.', '规划回读模式。'],
  ['GENERATE_PLAN', 'core', false, true, 'never', 'true', 'Generate a plan before execution.', '执行前生成计划。'],
  ['PLANNER_MODEL', 'core', false, true, 'never', null, 'Optional planner model override.', '可选的规划模型覆盖。'],
  ['PROGRESS_BUBBLES', 'core', false, true, 'never', 'milestones', 'Progress bubble display mode.', '进度气泡显示模式。'],
  ['CAPABILITIES_CONFIG', 'core', false, true, 'never', '~/.nova-audio-agent/capabilities.json', 'Capabilities registry path.', '能力注册表路径。'],
  ['SEARCH_PROVIDER', 'search', false, true, 'never', 'tavily', 'CLI or CI search provider override.', 'CLI 或 CI 搜索提供方覆盖。'],
  ['SEARCH_MCP_URL', 'search', false, true, 'never', null, 'Web search MCP endpoint override; unset uses the verified Bailian preset when MCP is selected.', '网页搜索 MCP 地址覆盖；选择 MCP 且未设置时使用已核对的百炼预设。'],
  ['SEARCH_MCP_TOOL', 'search', false, true, 'never', 'web_search', 'Web search MCP tool override (generic default web_search; Bailian preset search_pro).', '网页搜索 MCP 工具覆盖（通用默认 web_search；百炼预设 search_pro）。'],
  ['MEMORY_PRERECALL_ENABLED', 'core', false, true, 'never', 'false', 'Optionally prefetch context for text replies; voice uses profile and summary.', '文本回复可选预检索；语音默认使用个人资料与摘要。'],
  ['MEMORY_CONSOLIDATION_ENABLED', 'core', false, true, 'never', 'true', 'Generate derived memory summaries daily.', '每日生成派生记忆摘要。'],
  ['MEMORY_CONSOLIDATION_HOUR', 'core', false, true, 'never', '0', 'Local hour for daily memory consolidation (0-23).', '每日记忆整理时间（0-23 时）。'],
  ['MEMORY_CONSOLIDATION_TIMEZONE', 'core', false, true, 'never', 'UTC', 'IANA timezone for daily memory consolidation.', '每日记忆整理采用的 IANA 时区。'],
  ['KNOWLEDGE_PATH', 'core', false, true, 'never', '~/.nova-audio-agent/knowledge.sqlite', 'Knowledge SQLite database path.', '知识库 SQLite 数据库路径。'],
  ['EMBEDDING_PROVIDER', 'core', false, true, 'never', 'dashscope', 'Knowledge embedding provider.', '知识库 embedding 提供方。'],
  ['EMBEDDING_MODEL', 'core', false, true, 'never', 'text-embedding-v4', 'Knowledge embedding model.', '知识库 embedding 模型。'],
  ['MEMORY_BACKEND', 'core', false, false, 'never', null, 'Removed; rejected in favor of MEMORY_CONNECTION.', '已移除；使用时会报错，请改用 MEMORY_CONNECTION。'],
  ['MEMORY_CONNECTION', 'core', false, true, 'never', 'local', 'Memory connection: disabled, local, or remote.', '记忆连接：disabled、local 或 remote。'],
  ['MEMORY_PROVIDER', 'core', false, true, 'never', null, 'Local engine: voicemem (default; unified ledger) or explicit mem0. Remote engines are service-owned.', '本地引擎：voicemem（默认，统一账本）或显式选择 mem0。远程引擎由服务端选择。'],
  ['BLACKBOARD_PATH', 'core', false, true, 'never', '~/.nova-audio-agent/blackboard.sqlite', 'Conversation recovery database path.', '会话恢复数据库路径。'],
  ['BLACKBOARD_OWNER_ID', 'core', false, true, 'never', 'local', 'Stable conversation recovery owner.', '稳定的会话恢复所有者。'],
  ['MEMORY_URL', 'core', false, true, 'when_selected', null, 'HTTP memory service origin; HTTPS or numeric loopback HTTP.', 'HTTP 记忆服务地址；仅 HTTPS 或数字回环 HTTP。'],
  ['MEMORY_TOKEN', 'core', true, true, 'when_selected', null, 'Host-issued identity-bound memory bearer token.', '宿主提供的身份绑定记忆令牌。'],
  ['MEMORY_PATH', 'core', false, true, 'never', '~/.nova-audio-agent/memory.sqlite', 'Personal memory database path.', '个人记忆数据库路径。'],
  ['MEMORY_USER_ID', 'core', false, true, 'never', 'local', 'Stable personal memory user identity.', '稳定的个人记忆用户身份。'],
  ['DASHSCOPE_API_KEY', 'qwen', true, true, 'when_selected', null, 'Qwen realtime credential.', 'Qwen 实时凭据。'],
  ['QWEN_REALTIME_URL', 'qwen', false, true, 'never', 'DashScope realtime endpoint', 'Qwen secure realtime endpoint.', 'Qwen 安全实时地址。'],
  ['QWEN_REALTIME_MODEL', 'qwen', false, true, 'never', 'qwen-audio-3.0-realtime-plus', 'Qwen realtime model.', 'Qwen 实时模型。'],
  ['QWEN_REALTIME_VOICE', 'qwen', false, true, 'never', 'longanqian', 'Qwen realtime voice.', 'Qwen 实时音色。'],
  ['STEPFUN_API_KEY', 'stepfun', true, true, 'when_selected', null, 'StepFun realtime credential.', 'StepFun 实时凭据。'],
  ['STEPFUN_REALTIME_URL', 'stepfun', false, true, 'never', 'wss://api.stepfun.com/v1/realtime', 'StepFun secure realtime endpoint.', 'StepFun 安全实时地址。'],
  ['STEPFUN_REALTIME_MODEL', 'stepfun', false, true, 'never', 'stepaudio-3-realtime-preview', 'StepFun realtime model.', 'StepFun 实时模型。'],
  ['STEPFUN_REALTIME_VOICE', 'stepfun', false, true, 'never', '', 'StepFun realtime voice; empty uses the service default.', 'StepFun 实时音色；留空使用服务默认音色。'],
  ['QWEN_CONTROLLED_GUARD_RECONNECT', 'qwen', false, true, 'never', 'false', 'Allow controlled Guard reconnect.', '允许受控 Guard 重连。'],
  ['QWEN_GUARD_HISTORY_RECOVERY', 'qwen', false, true, 'never', 'none', 'Guard history recovery mode.', 'Guard 历史恢复模式。'],
  ['QWEN_GUARD_HISTORY_PAIRS', 'qwen', false, true, 'never', '4', 'Guard history pair count.', 'Guard 历史对话对数。'],
  ['DEEPSEEK_API_KEY', 'deepseek', true, true, 'when_selected', null, 'Official DeepSeek cascaded LLM credential.', 'DeepSeek 官方级联 LLM 凭据。'],
  ['ARK_API_KEY', 'ark', true, true, 'when_selected', null, 'Ark cascaded LLM credential.', '方舟级联 LLM 凭据。'],
  ['DOUBAO_ASR_API_KEY', 'volcengine', true, true, 'never', 'Doubao big-model key', 'Volcengine ASR credential override.', '火山 ASR 凭据覆盖。'],
  ['DOUBAO_BIGMODEL_API_KEY', 'volcengine', true, true, 'when_selected', null, 'Volcengine TTS and ASR fallback credential.', '火山 TTS 及 ASR 回退凭据。'],
  ['VOLCENGINE_ARK_BASE_URL', 'ark', false, true, 'never', 'Volcengine Ark endpoint', 'Ark secure endpoint.', '方舟安全地址。'],
  ['DOUBAO_ASR_ENDPOINT', 'volcengine', false, true, 'never', 'Doubao ASR endpoint', 'Doubao ASR secure endpoint.', '豆包 ASR 安全地址。'],
  ['DOUBAO_ASR_RESOURCE_ID', 'volcengine', false, true, 'never', 'volc.seedasr.sauc.duration', 'Doubao ASR resource ID.', '豆包 ASR 资源 ID。'],
  ['DOUBAO_ASR_VOICEPRINT_ENABLED', 'volcengine', false, true, 'never', 'false', 'Verify the registered speaker before accepting ASR text.', '只接收已注册说话人的 ASR 文本。'],
  ['DOUBAO_ASR_VOICEPRINT_ID', 'volcengine', false, true, 'never', '', 'Registered voiceprint UUID.', '已注册声纹 UUID。'],
  ['DOUBAO_ASR_VOICEPRINT_HEALTH_URL', 'volcengine', false, true, 'never', '', 'Disable verification when this HTTPS health endpoint is unavailable.', '健康检查失败时停用声纹验证的 HTTPS 地址。'],
  ['DOUBAO_ASR_VOICEPRINT_NAME', 'volcengine', false, true, 'never', '', 'Exact registered SpeakerName.', '注册时的完整 SpeakerName。'],
  ['DOUBAO_ASR_CHUNK_MS', 'volcengine', false, true, 'never', '200', 'ASR input chunk duration.', 'ASR 输入分块时长。'],
  ['DOUBAO_TTS_ENDPOINT', 'volcengine', false, true, 'never', 'Doubao TTS endpoint', 'Doubao TTS secure endpoint.', '豆包 TTS 安全地址。'],
  ['DOUBAO_TTS_RESOURCE_ID', 'volcengine', false, true, 'never', 'seed-tts-2.0', 'Doubao TTS resource ID.', '豆包 TTS 资源 ID。'],
  ['DOUBAO_TTS_VOICE', 'volcengine', false, true, 'never', 'zh_female_vv_uranus_bigtts', 'Doubao TTS voice.', '豆包 TTS 音色。'],
  ['DOUBAO_TTS_OUTPUT_SAMPLE_RATE', 'volcengine', false, true, 'never', '24000', 'Doubao TTS output sample rate.', '豆包 TTS 输出采样率。'],
  ['VOLCENGINE_VAD_THRESHOLD', 'volcengine', false, true, 'never', '0.5', 'VAD speech threshold.', 'VAD 语音阈值。'],
  ['VOLCENGINE_VAD_PRE_ROLL_MS', 'volcengine', false, true, 'never', '260', 'VAD pre-roll duration.', 'VAD 预滚时长。'],
  ['VOLCENGINE_VAD_MIN_SPEECH_MS', 'volcengine', false, true, 'never', '250', 'VAD minimum speech duration.', 'VAD 最短语音时长。'],
  ['VOLCENGINE_VAD_SILENCE_END_MS', 'volcengine', false, true, 'never', '300', 'VAD silence endpoint duration.', 'VAD 静音断句时长。'],
  ['VOLCENGINE_VAD_SPEECH_PAD_MS', 'volcengine', false, true, 'never', '30', 'VAD speech padding.', 'VAD 语音补边。'],
  ['VOLCENGINE_VAD_MAX_UTTERANCE_MS', 'volcengine', false, true, 'never', '60000', 'VAD maximum utterance duration.', 'VAD 最长话语时长。'],
  ['CODEX_WORKSPACE', 'codex', false, true, 'when_selected', null, 'Host-approved Codex workspace.', '主机批准的 Codex 工作区。'],
  ['CODEX_BIN', 'codex', false, true, 'never', 'codex', 'Host-approved Codex app-server binary.', '主机批准的 Codex app-server 可执行文件。'],
  ['CODEX_PREFIX_ARGS', 'codex', false, false, 'never', '[]', 'Host-approved direct argv prefix for an official Codex launcher.', '宿主批准的官方 Codex 启动器直接 argv 前缀。'],
  ['FEISHU_CLI_PATH', 'host_private', false, false, 'never', 'lark-cli', 'Host-configured Feishu CLI executable, version 1.0.69 or newer.', '宿主配置的飞书 CLI 路径，版本至少 1.0.69。'],
  ['CODEX_RESOURCES_PATH', 'codex', false, false, 'never', 'codex', 'Host-owned native resource root.', '宿主持有的原生资源根目录。'],
  ['CODEX_API_KEY', 'codex', true, true, 'never', 'Codex login', 'Optional Codex credential override.', '可选 Codex 凭据覆盖。'],
  ['CODEX_PREWARM', 'codex', false, true, 'never', 'true', 'Prewarm Codex app-server.', '预热 Codex app-server。'],
  ['CODEX_MANAGED_ROOT', 'codex', false, true, 'never', '~/.nova-audio-agent/workspaces', 'Managed project root.', '托管项目根目录。'],
  ['CODEX_PROJECT_STATE_ROOT', 'codex', false, true, 'never', '~/.nova-audio-agent', 'Project state root.', '项目状态根目录。'],
  ['CODEX_WORKING_INTERVAL', 'codex', false, true, 'never', '30', 'Codex progress interval in seconds.', 'Codex 进度间隔秒数。'],
  ['TAVILY_API_KEY', 'search', true, true, 'when_selected', null, 'Tavily search credential.', 'Tavily 搜索凭据。'],
  ['DESKTOP_VIDEO_FILE', 'camera', false, true, 'never', null, 'Absolute deterministic desktop video input.', '桌面确定性视频输入的绝对路径。'],
  ['REALTIME_TELEMETRY', 'telemetry', false, true, 'never', '~/.nova-audio-agent/realtime-telemetry.jsonl', 'Source-runtime telemetry output path; set an empty value to disable.', '源码运行时遥测输出路径；设置为空值可禁用。'],
  ['NOVA_ORB_OPAQUE', 'core', false, true, 'never', '0', 'Use an opaque desktop orb window.', '使用不透明桌面悬浮球窗口。'],
  ['SERVER_PORT', 'host_private', false, false, 'when_selected', null, 'Fixed loopback remote server port.', '远程服务固定本地端口。'],
  ['SERVER_TOKEN_FILE', 'host_private', true, false, 'when_selected', null, 'Absolute path to the private remote credential file.', '远程服务私有凭据文件的绝对路径。'],
  ['DESKTOP_TOKEN', 'host_private', true, false, 'when_selected', null, 'Desktop transport handshake token.', '桌面传输握手令牌。'],
  ['DESKTOP_READY_ENDPOINT', 'host_private', false, false, 'when_selected', null, 'Desktop readiness endpoint.', '桌面就绪端点。'],
  ['DESKTOP_READY_FD', 'host_private', false, false, 'never', null, 'Legacy desktop readiness descriptor.', '旧桌面就绪描述符。'],
  ['DEV_BACKEND_ENTRY', 'host_private', false, false, 'never', null, 'Unpackaged desktop backend entry override.', '未打包桌面的开发后端入口覆盖。'],
  ['DEV_START_MUTED', 'host_private', false, false, 'never', null, 'Start the unpackaged desktop with microphone muted.', '未打包桌面以闭麦状态启动。'],
  ['RELEASE_CAMERA_SMOKE', 'host_private', false, false, 'never', null, 'Packaged release camera capability sentinel.', '安装包发布相机能力哨兵。'],
  ['RELEASE_SMOKE', 'host_private', false, false, 'never', null, 'Authenticated packaged lifecycle smoke mode.', '安装包认证生命周期冒烟模式。'],
  ['DEVELOPER_DIR', 'host_private', false, false, 'never', null, 'Host Xcode developer directory used when binding an iOS Simulator.', '绑定 iOS 模拟器时使用的宿主 Xcode 开发者目录。'],
  ['CODEX_HOME', 'host_private', false, false, 'never', null, 'Host Codex credential home.', '主机 Codex 凭据目录。'],
  ['HOME', 'host_private', false, false, 'never', null, 'Host home directory.', '主机用户目录。'],
  ['MOBILE_ENGINE', 'mobile', false, true, 'never', 'midscene', 'Phone execution engine; currently midscene only.', '手机执行引擎；当前仅支持 midscene。'],
  ['MOBILE_DEVICE_TYPE', 'mobile', false, true, 'never', 'ios-simulator', 'Phone platform: android, ios or ios-simulator; native execution supports Android ADB and iOS Simulator.', '手机平台：android、ios 或 ios-simulator；原生执行支持 Android ADB 和 iOS 模拟器。'],
  ['MOBILE_DEVICE_ID', 'mobile', false, true, 'when_selected', null, 'Exact iOS device or Simulator UDID, or Android ADB serial.', '明确的 iOS 设备或模拟器 UDID，或 Android ADB 序列号。'],
  ['MOBILE_WDA_URL', 'mobile', false, true, 'never', 'http://127.0.0.1:8100', 'WebDriverAgent endpoint for the configured iOS device.', '配置的 iOS 设备 WebDriverAgent 地址。'],
  ['MOBILE_BASE_URL', 'mobile', false, true, 'when_selected', null, 'Phone model endpoint receiving screenshots.', '接收手机截图的模型服务地址。'],
  ['MOBILE_MODEL', 'mobile', false, true, 'when_selected', null, 'Phone model identifier.', '手机操作模型名称。'],
  ['MOBILE_MODEL_FAMILY', 'mobile', false, true, 'when_selected', null, 'Explicit model family used by the phone execution engine.', '手机执行引擎使用的明确模型系列。'],
  ['MOBILE_API_KEY', 'mobile', true, true, 'when_selected', null, 'Phone model credential.', '手机操作模型凭据。'],
  ['MOBILE_MAX_STEPS', 'mobile', false, true, 'never', '30', 'Supervised phone task step limit (1-100).', '受监督手机任务步骤上限（1-100）。'],
  ['MOBILE_TIMEOUT_SECONDS', 'mobile', false, true, 'never', '600', 'Phone task deadline (1-1800 seconds).', '手机任务截止时间（1-1800 秒）。'],
  ['MOBILE_SETTLE_MS', 'mobile', false, true, 'never', '4000', 'Screen settling delay before the first observation and after actions (0-30000 milliseconds).', '首次观察前及动作后等待画面稳定的时间（0-30000 毫秒）。'],
  ['AUTOGLM_PYTHON', 'autoglm', false, true, 'when_selected', null, 'Absolute AutoGLM Python executable.', 'AutoGLM Python 可执行文件绝对路径。'],
  ['AUTOGLM_SOURCE_PATH', 'autoglm', false, true, 'when_selected', null, 'Pinned Open-AutoGLM checkout.', '固定版本 Open-AutoGLM 目录。'],
  ['AUTOGLM_DEVICE_ID', 'autoglm', false, true, 'when_selected', null, 'Exact iOS UDID or Android ADB serial.', '明确的 iOS UDID 或 Android ADB 序列号。'],
  ['AUTOGLM_DEVICE_TYPE', 'autoglm', false, true, 'never', 'ios', 'Phone platform: ios, ios-simulator or android.', '手机平台：ios、ios-simulator 或 android。'],
  ['AUTOGLM_WDA_URL', 'autoglm', false, true, 'never', 'http://127.0.0.1:8100', 'WebDriverAgent endpoint for the configured iOS device.', '配置的 iOS 设备 WebDriverAgent 地址。'],
  ['AUTOGLM_BASE_URL', 'autoglm', false, true, 'when_selected', null, 'Phone model endpoint receiving screenshots.', '接收手机截图的模型服务地址。'],
  ['AUTOGLM_MODEL', 'autoglm', false, true, 'when_selected', null, 'Phone model identifier.', '手机操作模型名称。'],
  ['AUTOGLM_API_KEY', 'autoglm', true, true, 'when_selected', null, 'Phone model credential.', '手机操作模型凭据。'],
  ['AUTOGLM_MAX_STEPS', 'autoglm', false, true, 'never', '30', 'Supervised phone task step limit (1-100).', '受监督手机任务步骤上限（1-100）。'],
  ['AUTOGLM_TIMEOUT_SECONDS', 'autoglm', false, true, 'never', '600', 'Phone task deadline (1-1800 seconds).', '手机任务截止时间（1-1800 秒）。'],
  ['CODING_BACKEND', 'core', false, true, 'never', 'codex', 'Backend for new coding sessions: codex, opencode, codebuddy, pi or deepseek. Existing sessions keep theirs.', '新编程会话使用的执行器：codex、opencode、codebuddy、pi 或 deepseek；已有会话保持原执行器。'],
  ['CODING_PROFILES', 'host_private', false, false, 'never', null, 'Desktop-supplied registry of immutable ACP configuration-source profiles.', '桌面端提供的不可变 ACP 配置来源档案。'],
  ['OPENCODE_ACP_BIN', 'core', false, true, 'never', 'opencode on PATH', 'Absolute path to the OpenCode executable used for ACP.', '用于 ACP 的 OpenCode 可执行文件绝对路径。'],
  ['CODEBUDDY_ACP_BIN', 'core', false, true, 'never', 'codebuddy on PATH', 'Absolute path to the CodeBuddy executable used for ACP.', '用于 ACP 的 CodeBuddy 可执行文件绝对路径。'],
  ['PI_ACP_BIN', 'core', false, true, 'never', 'pi-acp on PATH', 'Absolute path to the pi-acp adapter executable.', 'pi-acp 适配器可执行文件绝对路径。'],
  ['DEEPSEEK_ACP_BIN', 'core', false, true, 'never', 'dsh on PATH', 'Absolute path to the DeepSeek Harness (dsh) executable used for ACP.', '用于 ACP 的 DeepSeek Harness（dsh）可执行文件绝对路径。'],
  ['CODING_MODULE_ENABLED', 'codex', false, true, 'never', 'true', 'Enable the coding module; the desktop turns it off when no Codex CLI is available.', '启用编程模块；桌面端在找不到 Codex CLI 时自动关闭。'],
] as const

export const environmentContract: readonly EnvironmentVariableContract[] = Object.freeze(rows.map(
  ([name, owner, secret, publicValue, required, defaultLabel, descriptionEn, descriptionZh]) =>
    Object.freeze({
      name,
      owner,
      secret,
      public: publicValue,
      required,
      defaultLabel,
      descriptionEn,
      descriptionZh,
    }),
))

export function publicEnvironmentContract(): readonly EnvironmentVariableContract[] {
  return Object.freeze(environmentContract.filter(entry => entry.public))
}
